//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChessOpening
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public long GameId { get; set; }
        public long PlayerWhite { get; set; }
        public long PlayerBlack { get; set; }
        public byte Result { get; set; }
        public Nullable<int> Debut { get; set; }
        public byte GameType { get; set; }
        public Nullable<System.DateTime> TimeToPlay { get; set; }
        public Nullable<System.DateTime> AddTimeToMove { get; set; }
        public Nullable<short> NumberMoves { get; set; }
        public Nullable<System.DateTime> DateGame { get; set; }
    
        public virtual Debut Debut1 { get; set; }
        public virtual GameType GameType1 { get; set; }
        public virtual Player Player { get; set; }
        public virtual Player Player1 { get; set; }
        public virtual ResultGame ResultGame { get; set; }
    }
}
