//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChessOpening
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_DebutStatistic
    {
        public long GameId { get; set; }
        public string TitleDebut { get; set; }
        public string TitleResult { get; set; }
        public string ConditionGameFinish { get; set; }
        public Nullable<System.DateTime> DateGame { get; set; }
    }
}
