//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChessOpening
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_PlayerInfo
    {
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Пол { get; set; }
        public string Страна { get; set; }
        public Nullable<System.DateTime> Дата_рождения { get; set; }
        public string Разряд { get; set; }
        public string Полное_название_разряда { get; set; }
        public short Рейтинг { get; set; }
    }
}
